### ISSUE TITLE
Windows lib not building

### ISSUE THREAD

**Issue by fred-dev** [elliotwoods/ofxBlackmagic2#14]
I get errors with the master branch of OF and this addon, just trying to run the simple example included.

\ofxBlackmagic2\src\ofxBlackMagic\Input.cpp	137	

`'->ofTexture::loadData': left operand has 'class' type, use '.'	ofxBlackmagicLib	
`

openFrameworks\addons\ofxBlackmagic2\src\ofxBlackMagic\Input.cpp	137	

`Error	C3867	'ofPixels_<unsigned char>::getData': non-standard syntax; use '&' to create a pointer to member	ofxBlackmagicLib	`

Does this rely on a specific commit of OF?

**Comment by elliotwoods** [comment]
hey fred!

seems there was a typo when it was updated for oF 0.1.0 compatability (when `ofPixels::getPixels()` was dropped).

i think i've fixed it:
https://github.com/elliotwoods/ofxBlackmagic2/blob/master/src/ofxBlackMagic/Input.cpp#L137

**Comment by elliotwoods** [comment]
let me know if this works, i'll close for the time being unless you report there's still an issue

**Comment by elliotwoods** [comment]
(thanks for the spot!)
